### ISSUE TITLE
Filtering across relations throws keyerror in latest package

### ISSUE THREAD

**Issue by mlissner** [philipn/django-rest-framework-filters#168]
(This might be a dup of #134, but I'm starting fresh so we have a cleaner bug.)

In https://github.com/freelawproject/courtlistener/issues/665 I'm in the process of upgrading from 

    djangorestframework-filters==0.6.0

To: 

    djangorestframework-filters==0.9.1

I'm also upgrading DRF and all of it's requirements at the same time. When I completed the upgrade using pip, several of my unit tests began failing with errors like:

```
Error
Traceback (most recent call last):
  File "/home/mlissner/Programming/intellij/courtlistener/cl/api/tests.py", line 372, in test_circular_relationships
    assertCount(self, path, q, 0)
  File "/home/mlissner/Programming/intellij/courtlistener/cl/api/tests.py", line 170, in assertCount
    r = cls.client.get(path, q)
  File "/home/mlissner/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/test/client.py", line 500, in get
    **extra)
  File "/home/mlissner/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/test/client.py", line 303, in get
    return self.generic('GET', path, secure=secure, **r)
  File "/home/mlissner/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/test/client.py", line 379, in generic
    return self.request(**r)
  File "/home/mlissner/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/test/client.py", line 466, in request
    six.reraise(*exc_info)
  File "/home/mlissner/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mlissner/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/mlissner/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/rest_framework/viewsets.py", line 83, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mlissner/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/mlissner/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mlissner/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/mlissner/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/rest_framework/mixins.py", line 40, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/mlissner/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/rest_framework/generics.py", line 151, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "/home/mlissner/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/rest_framework_filters/backends.py", line 18, in filter_queryset
    return filter_class(request.query_params, queryset=queryset).qs
  File "/home/mlissner/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/rest_framework_filters/filterset.py", line 326, in qs
    qs = super(FilterSet, self).qs
  File "/home/mlissner/.virtualenvs/courtlistener/local/lib/python2.7/site-packages/django_filters/filterset.py", line 335, in qs
    value = self.form.cleaned_data[name]
KeyError: 'person__positions__job_title__icontains'
```

I have some complicated models that have a lot of relations, but these tests passed just fine before the upgrade. Something seems to be wrong with the latest package or perhaps my configuration of it. Here's what I've got set up:

### Filters
```python
BASIC_TEXT_LOOKUPS = ['exact', 'iexact', 'startswith', 'istartswith',
                      'endswith', 'iendswith']
ALL_TEXT_LOOKUPS = BASIC_TEXT_LOOKUPS + ['contains', 'icontains']
class EducationFilter(filters.FilterSet):
    person = filters.RelatedFilter(
        'cl.people_db.filters.PersonFilter',
        name='person',
        queryset=Person.objects.all(),
    )

    class Meta:
        model = Education


class PositionFilter(filters.FilterSet):
    class Meta:
        model = Position
        fields = {
            'job_title': ALL_TEXT_LOOKUPS,
        }


class PersonFilter(filters.FilterSet):
    positions = filters.RelatedFilter(
        PositionFilter,
        name='positions',
        queryset=Position.objects.all(),
    )
    class Meta:
        model = Person
```

### Views

```python
class EducationViewSet(LoggingMixin, viewsets.ModelViewSet):
    queryset = Education.objects.all()
    serializer_class = EducationSerializer
    filter_class = EducationFilter
    ordering_fields = ('date_created', 'date_modified')
```

### Filter backends

```python
    # Filtering
    'DEFAULT_FILTER_BACKENDS': (
        # 'cl.api.utils.DisabledHTMLFilterBackend',
        'rest_framework_filters.backends.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
    ),
```

I've been trying to sort this out all day now and I'm pretty stumped. It makes the upgrade to the latest DRF pretty much impossible for our API.

**Comment by rpkilby** [comment]
Hi @mlissner - I'll take a look at the freelaw project later. In the mean time, could you try upgrading to django-filter 1.x and the master branch of drf-filters? I'm curious if this problem hasn't already been resolved.

**Comment by rpkilby** [comment]
Hey. I've been doing a little poking around, and it looks like this may be an interaction with `crispy_forms`. See https://github.com/carltongibson/django-filter/pull/696. In short, the crispy helper code is causing a premature cache of the form object, which will not contain the related filters.

**Comment by rpkilby** [comment]
I did a little more poking around in courtlistener and saw that you only use `crispy_forms` for DRF's browsable API. The easiest path forward is to temporarily remove `'crispy_forms'` from your `INSTALLED_APPS` until https://github.com/carltongibson/django-filter/pull/696 is merged/released. Let me know if that fixes the problem.

**Comment by mlissner** [comment]
I uninstalled crispy-forms and all tests are passing. Wow, thank you for resolving this so quickly. Never thought that a simple template helper would bring things down so horribly! Would have taken me a long time to figure this one out. 

It looks like you're resolving this in carltongibson/django-filter#696. Any other reason to keep this bug open? 

Thank you again!

**Comment by rpkilby** [comment]
> Never thought that a simple template helper would bring things down so horribly!

It's technically not the fault of crispy forms, just a little bit of helper code that hasn't ever been tested. Once 696 is merged, it should be safe to use crispy forms again.

> Any other reason to keep this bug open?

Nope :)

**Comment by rpkilby** [comment]
Hi @mlissner, django-filter 1.1 has been released, which includes the referenced fix.

**Comment by mlissner** [comment]
Great news! Thank you so much!
