### ISSUE TITLE
whenever i include the package in installed apps i get this error

### ISSUE THREAD

**Issue by tluanga** [philipn/django-rest-framework-filters#277]
```python
(pro1-w0duipED) λ python manage.py runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x00000252A5E492F0>
Traceback (most recent call last):
  File "C:\Users\tluanga\.virtualenvs\pro1-w0duipED\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\tluanga\.virtualenvs\pro1-w0duipED\lib\site-packages\django\core\management\commands\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\tluanga\.virtualenvs\pro1-w0duipED\lib\site-packages\django\utils\autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "C:\Users\tluanga\.virtualenvs\pro1-w0duipED\lib\site-packages\django\core\management\__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\tluanga\.virtualenvs\pro1-w0duipED\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\tluanga\.virtualenvs\pro1-w0duipED\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\tluanga\.virtualenvs\pro1-w0duipED\lib\site-packages\django\apps\registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\tluanga\.virtualenvs\pro1-w0duipED\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "C:\Users\tluanga\.virtualenvs\pro1-w0duipED\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\tluanga\.virtualenvs\pro1-w0duipED\lib\site-packages\rest_framework_filters\__init__.py", line 3, in <module>
    from .filterset import FilterSet
  File "C:\Users\tluanga\.virtualenvs\pro1-w0duipED\lib\site-packages\rest_framework_filters\filterset.py", line 10, in <module>
    from django_filters import filterset, rest_framework
  File "C:\Users\tluanga\.virtualenvs\pro1-w0duipED\lib\site-packages\django_filters\__init__.py", line 7, in <module>
    from .filterset import FilterSet
  File "C:\Users\tluanga\.virtualenvs\pro1-w0duipED\lib\site-packages\django_filters\filterset.py", line 15, in <module>
    from .filters import (
  File "C:\Users\tluanga\.virtualenvs\pro1-w0duipED\lib\site-packages\django_filters\filters.py", line 9, in <module>
    from django.db.models.sql.constants import QUERY_TERMS
ImportError: cannot import name 'QUERY_TERMS' from 'django.db.models.sql.constants' (C:\Users\tluanga\.virtualenvs\pro1-w0duipED\lib\site-packages\django\db\models\sql\constants.py)
```

**Comment by menecio** [comment]
`django-rest-framework-filters==0.10.2.post0` is not compatible with `django>=2.0`

**Comment by rpkilby** [comment]
Hi @tluanga. You either want upgrade to the drf-filters `1.0.0.dev0` release, or you'll want to downgrade to Django `1.11`.
