### ISSUE TITLE
Attribute error on FilterSet

### ISSUE THREAD

**Issue by uber1geek** [philipn/django-rest-framework-filters#313]
> AttributeError: module 'django_filters.rest_framework.filters' has no attribute 'FilterSet'

```from django_filters.rest_framework import FilterSet, filters```
```
 "djangorestframework-filters": 
            "version": "==1.0.0.dev0"
 "django-filter": 
            "version": "==2.2.0"        
"django": 
            "version": "==2.2.5"
```

**Comment by rpkilby** [comment]
Hi @uber1geek - could you provide the complete trace back?

**Comment by uber1geek** [comment]
@rpkilby Sure :)
```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/pathfinder/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/pathfinder/.pyenv/versions/3.6.5/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/pathfinder/.virtualenvs/mvp-2-vUfqe6mJ/lib/python3.6/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/Users/pathfinder/.virtualenvs/mvp-2-vUfqe6mJ/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/Users/pathfinder/.virtualenvs/mvp-2-vUfqe6mJ/lib/python3.6/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/pathfinder/.virtualenvs/mvp-2-vUfqe6mJ/lib/python3.6/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/pathfinder/.virtualenvs/mvp-2-vUfqe6mJ/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/pathfinder/.virtualenvs/mvp-2-vUfqe6mJ/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/Users/pathfinder/.virtualenvs/mvp-2-vUfqe6mJ/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/Users/pathfinder/.virtualenvs/mvp-2-vUfqe6mJ/lib/python3.6/site-packages/django/urls/resolvers.py", line 399, in check
    for pattern in self.url_patterns:
  File "/Users/pathfinder/.virtualenvs/mvp-2-vUfqe6mJ/lib/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/pathfinder/.virtualenvs/mvp-2-vUfqe6mJ/lib/python3.6/site-packages/django/urls/resolvers.py", line 584, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/pathfinder/.virtualenvs/mvp-2-vUfqe6mJ/lib/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/pathfinder/.virtualenvs/mvp-2-vUfqe6mJ/lib/python3.6/site-packages/django/urls/resolvers.py", line 577, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/pathfinder/.virtualenvs/mvp-2-vUfqe6mJ/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/pathfinder/nolin/urls.py", line 24, in <module>
    from ament.views import *
  File "/Users/pathfinder/nolin/properties/views.py", line 200, in <module>
    class SpacesFilter(filters.FilterSet):
AttributeError: module 'django_filters.rest_framework.filters' has no attribute 'FilterSet'
```

**Comment by rpkilby** [comment]
Thanks - this is an issue with the app code. It's attempting to import `FilterSet` from `django_filters.rest_framework.filters`, but it should instead be imported from `django_filters.rest_framework`. e.g.,

```python
from django_filters.rest_framework import FilterSet, filters
```

Also, it's worth noting that you're not actually using `djangorestframework-filters` here. This package's imports are under `rest_framework_filters`. e.g., 

```python
from rest_framework_filters import FilterSet, filters
```

Hope that helps.

**Comment by uber1geek** [comment]
@rpkilby  I have tried both and it doesn't seem to work, l

```
line 201, in <module>
    class SpacesFilter(filters.FilterSet):
AttributeError: module 'rest_framework_filters.filters' has no attribute 'FilterSet'
```

```
# from django_filters.rest_framework import FilterSet, filters
from rest_framework_filters import FilterSet, filters

class SpacesFilter(filters.FilterSet):
    name = filters.AllLookupsFilter()
    address = filters.AllLookupsFilter()
    space_type = filters.AllLookupsFilter()

    class Meta:
        model = Spaces```
